#### Mean Absolute Error
###### Using function

In [6]:
import numpy as np

In [7]:
y_predicted=np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])

In [15]:
def MAE(y_true,y_predicted):

    total_error=0
    for yt,yp in zip(y_true,y_predicted):
        total_error += abs(yt-yp)
    print("Total error:",total_error)
    mean_absolute_error=total_error/len(y_true)
    print("mean_absolute_error:",mean_absolute_error)

In [16]:
MAE(y_true,y_predicted)

Total error: 2.5
mean_absolute_error: 0.5


###### Using numpy module

In [23]:
np.abs(y_true-y_predicted)

array([0.7, 0.3, 1. , 0. , 0.5])

In [24]:
np.mean(np.abs(y_true-y_predicted))

0.5

#### Mean Square Error
###### using function

In [20]:
def MSE(y_true,y_predicted):
    total_error_mse=0
    for ytm,ypm in zip(y_true,y_predicted):
        total_error_mse+= (ytm-ypm)**2
    print("Total error:",total_error_mse)
    mean_square_error=total_error_mse/len(y_true)
    print("mean_square_error:",mean_square_error)
    

In [21]:
MSE(y_true,y_predicted)

Total error: 1.83
mean_square_error: 0.366


###### Using numpy module

In [25]:
np.square(y_true-y_predicted)

array([0.49, 0.09, 1.  , 0.  , 0.25])

In [26]:
np.mean(np.square(y_true-y_predicted))

0.366

#### Log loss 
###### Using function

In [35]:
eplison=1e-15

In [36]:
y_predicted_new=([max(i,eplison) for i in y_predicted])
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [37]:
y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [38]:
y_predicted_new=np.array(y_predicted_new)

In [39]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [40]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [43]:
def log_loss(y_true,y_predicted):
    eplison=1e-15
    y_predicted_new=([max(i,eplison) for i in y_predicted])
    y_predicted_new=[min(i,1-eplison) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    np.log(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [44]:
log_loss(y_true,y_predicted)

17.2696280766844